#!/bin/sh
# git-pr step 2: open a PR into main. Never auto-merges (§3 merge policy).
# Safe no-op when gh / GH_TOKEN are absent so a keyless run still ends cleanly.
set -eu
cd "${DEEPAGENTS_WORKSPACE:-.}"
. ./.deepagents/session.env

command -v gh >/dev/null 2>&1 || {
  echo "[workflow git-pr] gh not installed; skipping PR" >&2
  exit 0
}
if [ -z "${GH_TOKEN:-${GITHUB_TOKEN:-}}" ]; then
  echo "[workflow git-pr] no GH_TOKEN/GITHUB_TOKEN; skipping PR" >&2
  exit 0
fi

# Create only — human pre-review is mandatory before main integration (§3).
gh pr create \
  --title "Agent Run: ${DEEPAGENTS_SESSION_ID}" \
  --body "Automated PR generated by Deep Agents. **Manual review required. Auto-merge disabled.**" \
  --base main \
  --head "$DEEPAGENTS_SESSION_BRANCH" >&2 \
  || echo "[workflow git-pr] gh pr create failed (already exists / no remote?)" >&2
