#!/bin/sh
# git-pr step 2: open a PR into main. Never auto-merges (§3 merge policy).
# Safe no-op when gh / GH_TOKEN are absent so a keyless run still ends cleanly.
set -eu
cd "${DEEPAGENTS_WORKSPACE:-.}"
. "${DEEPAGENTS_STATE_DIR:-.deepagents}/session.env"
# Absolute, resolved while we are still in the workspace: the telemetry read below
# runs in a subshell that cds to /project, where the relative `.deepagents`
# fallback would silently point at the wrong directory.
STATE_DIR="${DEEPAGENTS_STATE_DIR:-$PWD/.deepagents}"

command -v gh >/dev/null 2>&1 || {
  echo "[workflow git-pr] gh not installed; skipping PR" >&2
  exit 0
}
if [ -z "${GH_TOKEN:-${GITHUB_TOKEN:-}}" ]; then
  echo "[workflow git-pr] no GH_TOKEN/GITHUB_TOKEN; skipping PR" >&2
  exit 0
fi

# Body is built into a temp file and passed with --body-file rather than as a
# --body literal (Milestone 6 T4): the telemetry block below is multi-line
# markdown with pipes and backticks, which is exactly the shape that makes shell
# quoting fragile. With no summary present the body is byte-identical to the
# hardcoded string this used to pass, so the no-telemetry path is unchanged.
BODY_FILE="$(mktemp)"
trap 'rm -f "$BODY_FILE"' EXIT
cat >"$BODY_FILE" <<'EOF'
Automated PR generated by Deep Agents. **Manual review required. Auto-merge disabled.**
EOF

# Append the run telemetry block, if there is one. Rendering happens in Python
# (harness.telemetry.render_pr_block, host-tested) and the shell only redirects
# it: formatting money and durations in sh is how a PR body ends up with
# "0.00000001" and "NaN".
#
# Two things this invocation has to get right:
#   * CWD -- we cd'd to the workspace above, and the harness package is not
#     installed, it is a directory at /project. So `-m harness` from here fails
#     with "No module named harness". Run it in a SUBSHELL that cds to /project,
#     because the `gh` call below still needs the workspace CWD.
#   * Interpreter -- prefer the harness venv explicitly. The workspace conda env
#     must never be the interpreter that imports harness code (the two-stack rule),
#     and on PATH it may well be the one `python3` resolves to.
#
# Any failure -- missing file, bad JSON, non-zero exit, missing interpreter --
# leaves the body at the text above and exits 0. The `|| true` wraps the block
# generation only, never the PR creation: a telemetry gap must not be the reason
# a PR does not open.
HARNESS_PY=/opt/venv/bin/python3
[ -x "$HARNESS_PY" ] || HARNESS_PY="$(command -v python3 || true)"
if [ -n "$HARNESS_PY" ]; then
  TELEMETRY_BLOCK="$(
    (cd /project && "$HARNESS_PY" -m harness telemetry pr-block \
        --state-dir "$STATE_DIR" 2>/dev/null) || true
  )"
  if [ -n "$TELEMETRY_BLOCK" ]; then
    printf '\n%s\n' "$TELEMETRY_BLOCK" >>"$BODY_FILE"
  fi
fi

# Create only — human pre-review is mandatory before main integration (§3).
gh pr create \
  --title "Agent Run: ${DEEPAGENTS_SESSION_ID}" \
  --body-file "$BODY_FILE" \
  --base main \
  --head "$DEEPAGENTS_SESSION_BRANCH" >&2 \
  || echo "[workflow git-pr] gh pr create failed (already exists / no remote?)" >&2
